import React from 'react'
import Head from 'next/head';
import NavSecond from '@/components/NavSecond';
import Link from 'next/link';

function Criminal() {
  return (
    <>
    <Head>
        <title>Criminal Law Service</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/services/criminal.png" />
      </Head>
      <NavSecond/>
      <section id='criminal' className='w-full h-screen flex items-center justify-center bg-black opacity-70' >
      <div className='text-center text-white'>
        <p className='text-2xl md:text-3xl font-bold'>Services</p>
        <h1 className='text-4xl md:text-6xl font-bold'>Criminal Law</h1>
        <Link href='/#contact' className='mt-8 inline-block py-4 px-8 text-lg font-semibold text-white border-2  bg-yellow-600 border-yellow-600 rounded-lg hover:scale-110 duration-200'>Get an appointment</Link>
      </div>
    </section>
    <div className='w-full md:h-full items-center mt-5 mb-16'>
        <h1 className='text-4xl md:text-6xl text-center text-yellow-500 mb-3 mt-3 md:mt-16 md:mb-16'>Criminal Law</h1>
        <div className='border-4 rounded-lg border-slate-400 mr-10 ml-10 md:ml-44 md:mr-44'>
        <div className='text-sm md:text-xl text-slate-600 mr-5 ml-5'>
        <p className='mt-3 border-solid border-2 rounded-lg p-3 '>Criminal law is the area of law that deals with crimes, criminal offenses, and their punishment. It is a branch of law that regulates the behavior of individuals, groups, and organizations to maintain public order and safety.</p>
        <p className='mt-3 border-solid border-2 rounded-lg p-3'>Our firm is dedicated to providing top-quality legal services in the area of criminal law. With our extensive experience and knowledge, we offer our clients the peace of mind that comes with knowing that their case is in good hands.</p>

        <p className='mt-3 border-solid border-2 rounded-lg p-3'>At our firm, we understand that facing criminal charges can be a stressful and daunting experience. That's why we strive to provide our clients with compassionate, yet aggressive representation. We work tirelessly to protect their rights and interests, and we are committed to achieving the best possible outcome for every client we represent.</p>

        <p className='mt-3 border-solid border-2 rounded-lg p-3'>Our team of skilled attorneys and legal professionals has a proven track record of success in defending clients against a wide range of criminal charges. We are well-versed in the law and we stay up-to-date on the latest developments in criminal defense strategies and techniques. This allows us to provide our clients with the most effective representation possible.</p>

        <p className='mt-3 border-solid border-2 rounded-lg p-3'>At our firm, we take a client-focused approach to every case we handle. We understand that each client's situation is unique, and we work closely with them to develop a personalized legal strategy that meets their specific needs and goals. We are dedicated to providing our clients with the highest level of service and support throughout the entire legal process.</p>

        <p className='mt-3 mb-3 border-solid border-2 rounded-lg p-3'>Whether you are facing a misdemeanor or a serious felony charge, our firm is here to help. We will fight tirelessly to protect your rights and help you achieve the best possible outcome in your case. <Link href="/#contact" className='text-yellow-500 hover:scale-110 duration-200'>Contact us</Link> today to schedule a consultation and learn more about how we can assist you.</p>
        </div>
        </div>
      </div>
    </>
  );
};

export default Criminal;