import Navbar from '@/components/Nav'
import Head from 'next/head'
import Main from '@/components/Main'
import About from '@/components/About'
import Services from '@/components/Services'
import Attorneys from '@/components/Attorneys'
import Free from '@/components/Free'
import Testimonial from '@/components/Testimonial'
import Contact from '@/components/Contact'

export default function Home() {
  return (
    <>
      <Head>
        <title>Lawyer Company Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type='png' href="/hammer.png" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Services/>
      <Attorneys/>
      <Free/>
      <Testimonial/>
      <Contact/>
    </>
  );
};
